//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class answers
    {
        public int Id { get; set; }
        public string User_name { get; set; }
        public int Question_option_id { get; set; }
    
        public virtual option_choices option_choices { get; set; }
        public virtual users users { get; set; }
    }
}
