//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class surveysdbEntities1 : DbContext
    {
        public surveysdbEntities1()
            : base("name=surveysdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answers> answers { get; set; }
        public virtual DbSet<input_types> input_types { get; set; }
        public virtual DbSet<option_choices> option_choices { get; set; }
        public virtual DbSet<questions> questions { get; set; }
        public virtual DbSet<surveys> surveys { get; set; }
        public virtual DbSet<text_answers> text_answers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
